export const BUILT_IN_COLOR_ARRAY = [
  { name: '', title: '', value: '#FFFFFF' },
  { name: '', title: '', value: '#989898' },
  { name: '', title: '', value: '#333333' },
  { name: '', title: '', value: '#000000' },
  { name: '', title: '', value: '#A22E00' },
  { name: '', title: '', value: '#9B6200' },
  { name: '', title: '', value: '#296400' },
  { name: '', title: '', value: '#006799' },
  { name: '', title: '', value: '#00346B' },
  { name: '', title: '', value: '#FF5D29' },
  { name: '', title: '', value: '#F9FE00' },
  { name: '', title: '', value: '#48FF00' },
  { name: '', title: '', value: '#009BFF' },
  { name: '', title: '', value: '#2F68FF' },
  { name: '', title: '', value: '#F90041' },
  { name: '', title: '', value: '#FFCA92' },
  { name: '', title: '', value: '#00CE93' },
  { name: '', title: '', value: '#58CFFF' },
  { name: '', title: '', value: '#6667FF' },
  { name: '', title: '', value: '#FFC9CD' },
  { name: '', title: '', value: '#FEFEC6' },
  { name: '', title: '', value: '#86FFC9' },
  { name: '', title: '', value: '#C4FFFD' },
  { name: '', title: '', value: '#CACCFF' }
]
